max_attempts: 5

login:
  username: "abdhahir.k@evonith.com"
  password: "Evonith2022@"
  url: "https://mcartalert.com/MeirCharts.aspx"
  user_id: "txtUsername"
  pwd_id: "txtPassword"
  btn_login_id: "btnLogin"

dates:
  start_date: "2024-01-17"
  end_date: "2024-08-08"
  start_time: "22:00"
  end_time: "22:00"
  delta_date: 15
  start_date_id: "PageContentHolder_calendarSelect"
  end_date_id: "PageContentHolder_calendarSelectEnd"
  start_time_id: "PageContentHolder_ddlStartingTime"
  end_time_id: "PageContentHolder_ddlEndTime"

variables:
  btn_apply_id: "PageContentHolder_btnApplyChanges"
  dwnld_btn_id: "PageContentHolder_ImageButton1"

wait_times:
  plot_wait: 20
  login_wait: 5
  variable_wait: 1
  popup_wait: 3
  UGML_wait: 2
  download_wait: 30